# Generated by Django 4.2.3 on 2023-07-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
