# Generated by Django 4.2.3 on 2023-07-12 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_vote_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterobj',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionFIlterObjs', to='base.question'),
        ),
    ]
