# Generated by Django 4.2.3 on 2023-07-08 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='survey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.survey'),
            preserve_default=False,
        ),
    ]
