# Generated by Django 4.2.3 on 2023-07-08 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_filter_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='base.survey'),
        ),
    ]
