# Generated by Django 4.2.3 on 2023-07-08 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_filter_survey'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterObj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.question')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filterObjs', to='base.survey')),
            ],
        ),
        migrations.DeleteModel(
            name='Filter',
        ),
    ]
